sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: cPxcG3ECUpf/yuTRWpWWyvAm406xZRfyQEJPtqsxjc8UWzTHqLDtFvTlS4vMygY56TmKltzXByso419DMzxb0j52K/cHFoFFzV+Eiobl/H4j5BZDji9j8IdOKAYofu1elQaQMv+okkoOjJIdKRWzDecRaQ9lP1k8ISGULvZtvX9/Q0qobByKzfkuB6/KrkMNMcwM2qn/RL47Qw7BjduKqY0t+2KdBqxcyUGdIKdAWINyNoYLZEikLFuggnaaHzFOnoKufRwBkD3RnS7pwaQZs83p1MjVKWqZIdCfBMCRNfjFb5RDU6sbjSQ626wt56QxkblpbY6Yh7Q36FvHiol/6Dwho9oGvW3w5k21+Zl2hi1wK8rjRZiUzDYp8spVouqibl13Iz/VMMxQrEB98ypAMZ89AaVydaLPNe8GfqKAYT/NMKfyugJeKnv4199dM5QBlOdLnR32QAv7z0JFduLd+ihTWlQSVdDv3AolhRY1xfBr4tQuOyANKsy53QSG3Tegt5kfg3yyqDItG5rGKINKfxmkJEqcS0uMY0CWj0IUYM5afNxuXjlmPqNeU2QuUkkMWmWFH3Y9ItZCx3U/cwaNaSVM21x8JjwbC5qXzXzqzfyqOG+p6Ff4u4Cwpxre9W8abA1j0J9UhWSgbO5qua1jrg9fBBwE/OaHcJZQLf+3oYU=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    rooms:
      secure: qUSJHhQjHFARdJel9CfD2BPsuj1t/aDh2t/cC0nMCv+RrSryGIxakOTSrQdV8Val5gaA0oB2A3c54bq1E9RHtwEpS1PwlMiftb5jv43DgWWn105hNxQdULCzH7eHXmH/rjihpAkSLuSTLpkLB7gMx9V+eEzofF/SLUUKdmEj9dhGkmUYKzRVibQNjez8EPBVCPGfetYsr/Qp/1ShMNKz5uEoeZxePAP1fEyOdZ58DwVT4NTcYMCrkVnSFlULykENKyjbjEp8mQiPYnoYEUDkcrIbY1NT6E2lAMLiIEiL8pxJw2MJ6rnMu+4FsJ8jKsftZmFPapsuLyiUgUnYyny9UuJ0uIxdYzMkEuhOeQng6MncveldTHlBRb+iIdaj72EggEE6hbnKldLjsm+ourJcqEbVW0MrbcYXo9yJ6yDcijQNmXXXOl1qX248eoIUf5yhi6UdyRUEdPKpW4/PGsOngIOQSbkCyCfEos7CFFvpTp9z/nX7imugrxmKUOAf27Xti4WQvCIZO3OAC2YCPg79Fq+BBIFf/bmpded2TPv7O8/hZfQ9CNAdOll/TdtS3SFcYkDqNFteVEAhVTOYXBNMlW2oKtwSrUgqzKhMXamXR7mKygvE16t0mLXEDhUZXM8OwzUO3Nb/KS/tBag1+Lrowdt8BYN3jJEGqPUohpcWrgI=
